# Generated by Django 6.0.7 on 2026-07-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=20)),
                ('colour', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
